spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/sys_batch?autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: sysbatch
    password: "q1w2e3r4T%"
    driver-class-name: com.mysql.cj.jdbc.Driver
